build: false

# See: https://www.appveyor.com/docs/windows-images-software/#miniconda
environment:
  matrix:
    - PYTHON: "C:\\Miniconda3"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda3"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
    # - PYTHON: "C:\\Miniconda3"
    #   PYTHON_VERSION: "3.7"
    #   PYTHON_ARCH: "32"
    # - PYTHON: "C:\\Miniconda3-x64"
    #   PYTHON_VERSION: "3.7"
    #   PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - set CONDA_CHANS="conda-forge defaults"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "python utils\\conda_create.py requirements\\base.yml --python_version=%PYTHON_VERSION% --channels %CONDA_CHANS% --ignore %CONDA_IGNORE% --run"
  - activate calliope
  - pip install --no-cache-dir .

test_script:
  - "py.test"
